<?php
if (!defined('ABSPATH')) exit;
function mestalla_theme_setup(){add_theme_support('title-tag');add_theme_support('post-thumbnails');register_nav_menus(['primary'=>'Menú principal']);}
add_action('after_setup_theme','mestalla_theme_setup');
function mestalla_assets(){wp_enqueue_style('mestalla-style',get_stylesheet_uri(),[],wp_get_theme()->get('Version'));}
add_action('wp_enqueue_scripts','mestalla_assets');
function mestalla_brandmark(){return '<svg class="crest" viewBox="0 0 64 74" role="img" aria-label="Escudo Mestalla Naranja"><path d="M8 5h48v35c0 14-10 24-24 30C18 64 8 54 8 40V5Z" fill="#f36b21" stroke="#fff" stroke-width="2"/><path d="M13 10h38v29c0 11-7 19-19 25-12-6-19-14-19-25V10Z" fill="#fff8f0"/><path d="m13 14 9-4 4 5 6-5 6 5 5-5 8 4v3H13Z" fill="#101c2c"/><path d="M16 26h32v5H16zm0 8h32v5H16zm0 8h32v5H16z" fill="#f36b21"/><circle cx="32" cy="59" r="4" fill="#101c2c"/><text x="32" y="23" text-anchor="middle" font-size="7" font-family="Arial" font-weight="700" fill="#101c2c">VCF</text></svg>';}
function mestalla_header(){?><div class="topbar"><div class="topbar-in"><span>ORGULLO DE MESTALLA <strong>· DESDE 1919</strong></span><span>VALENCIA · AMUNT SEMPRE</span></div></div><header class="site-nav"><div class="nav-in"><a class="brand" href="<?php echo esc_url(home_url('/')); ?>"><?php echo mestalla_brandmark(); ?><span>MESTALLA <small>ENTRADAS · VALENCIA CF</small></span></a><nav class="nav-links"><a href="<?php echo esc_url(home_url('/#partidos')); ?>">Partidos</a><a href="<?php echo esc_url(home_url('/#experiencia')); ?>">La experiencia</a><a href="<?php echo esc_url(home_url('/mi-cuenta/')); ?>">Mi cuenta</a><a class="btn" href="<?php echo esc_url(home_url('/entradas/')); ?>">Comprar entradas</a></nav></div></header><?php }
function mestalla_footer(){?><section class="cta"><div class="cta-in"><div><h2>El teu lloc està a Mestalla.</h2><p>Viu cada partit des de dins. Amunt València.</p></div><a class="btn dark" href="<?php echo esc_url(home_url('/entradas/')); ?>">Elige tu partido&nbsp; ↗</a></div></section><footer class="footer"><div class="footer-in"><span>© <?php echo esc_html(date('Y')); ?> MESTALLA ENTRADAS · Proyecto local de demostración</span><span>Una pasión que se vive en casa. &nbsp;|&nbsp; Valencia, España</span></div></footer><?php wp_footer(); ?></body></html><?php }
